# Generated by Django 2.2.4 on 2019-11-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review_comment_s_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_file',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='review_file',
            name='original_name',
        ),
        migrations.AlterField(
            model_name='review',
            name='s_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Store', to='app.Store'),
        ),
        migrations.CreateModel(
            name='Store_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('s_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Store')),
            ],
        ),
    ]
